# Generated by Django 4.0.4 on 2022-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='modified_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
